"""Regression tests for DCM and spectral DCM behaviour."""

import numpy as np
import pytest
from scipy.optimize import minimize

from dcsem import models, utils
from dcsem.spectral import SpectralDCM
from dcsem.validation import ShapeError


def _fit_spectral_lsq(spdcm, y_obs, theta_init):
    """Least-squares fit of SpectralDCM theta to a vectorised CSD observation.

    SpectralDCM has no built-in fitter, so this mirrors the normalised-MSE
    pattern used by spdcm_generic.run_single. Normalisation is critical:
    raw CSD values are O(1e-5) so the unscaled MSE collides with L-BFGS-B's
    default ftol and the optimiser stops at theta_init.
    """
    bounds = spdcm.get_bounds()
    scale = np.std(y_obs) + 1e-12

    def loss(theta):
        y_pred = spdcm.predict_csd(theta)
        if not np.all(np.isfinite(y_pred)):
            return 1e10
        return float(np.mean(((y_obs - y_pred) / scale) ** 2))

    return minimize(loss, theta_init, method="L-BFGS-B", bounds=bounds)


def test_dcm_negloglik_rejects_unstable_connectivity():
    dcm = models.DCM(2)
    A = np.array([[-1.0, 0.0], [0.2, -1.0]])
    C = np.array([1.0, 0.0])
    dcm.set_params({"A": A, "C": C})

    tvec = np.linspace(0, 20, 80)
    u = utils.stim_boxcar([[0, 5, 1]])
    y, _ = dcm.simulate(tvec, u=u)

    p_bad = dcm.get_p().copy()
    p_bad[dcm.get_p_names().index("a0_0")] = 0.1

    assert dcm.fn_negloglik(p_bad, y, tvec, u) == pytest.approx(1e12)


def test_dcm_nl_fit_respects_bounds_and_reports_uncertainty():
    dcm = models.DCM(2)
    A = np.array([[-2.0, 0.0], [0.3, -2.0]])
    C = np.array([1.0, 0.0])
    dcm.set_params({"A": A, "C": C})

    tvec = np.linspace(0, 20, 80)
    u = utils.stim_boxcar([[0, 5, 1]])
    y, _ = dcm.simulate(tvec, u=u)

    names = dcm.get_p_names()
    p0 = dcm.get_p().copy()
    p0[names.index("a1_0")] = 10.0
    p0[names.index("c0")] = 10.0
    fixed = [name for name in names if name not in {"a1_0", "c0"}]

    res = dcm.fit(y, tvec, u=u, p0=p0, method="NL", fixed_vars=fixed)

    assert res.success
    assert res.uncertainty_kind == "hessian_negloglik"
    # ``cov_is_calibrated`` can be False when the Hessian is borderline
    # indefinite (numdifftools picks up small negative eigenvalues from
    # finite-difference noise) and ``adaptive_ridge`` applies a significant
    # lift. Assert the two flags are *consistent*: uncalibrated iff
    # significant ridge was applied.
    if not res.cov_is_calibrated:
        assert res.covariance_diagnostics.get("regularization_warning") is True
    assert np.isclose(res.x[names.index("a1_0")], 0.3, atol=5e-2)
    assert np.isclose(res.x[names.index("c0")], 1.0, atol=5e-2)
    assert not res.at_bounds[names.index("a1_0")]
    assert not res.at_bounds[names.index("c0")]


def test_spectral_predict_csd_validates_theta_and_flags_instability():
    spdcm = SpectralDCM(n_rois=2, TR=1.0)
    assert spdcm.get_param_names() == ["a01", "a10", "log_sigma_e"]
    assert len(spdcm.get_bounds()) == len(spdcm.get_param_names())

    with pytest.raises(ValueError, match="theta has length"):
        spdcm.predict_csd(np.array([0.1, 0.2]))

    unstable = spdcm.predict_csd(np.array([2.5, 2.5, np.log(0.1)]))
    assert np.isinf(unstable).all()


def test_spectral_observed_csd_validation_and_smoke():
    spdcm = SpectralDCM(n_rois=2, TR=1.0)

    with pytest.raises(ShapeError):
        spdcm.observed_csd(np.random.randn(100))

    with pytest.raises(ValueError, match="nperseg"):
        spdcm.observed_csd(np.random.randn(100, 2), nperseg=1)

    theta = np.array([0.2, -0.1, np.log(0.3)])
    bold, _ = spdcm.simulate_bold(theta, T=60, rng=np.random.default_rng(0))
    csd = spdcm.observed_csd(bold, nperseg=20, noverlap=10)

    assert csd.shape == (spdcm._output_dim(),)
    assert np.all(np.isfinite(csd))


def test_spectral_recovers_theta_from_clean_csd():
    """Self-consistency: predict_csd(theta_true) -> fit -> recover theta_true.

    Pins current behaviour. Even with the H1 HRF double-count, fitting against
    data generated by the same buggy pipeline should recover theta_true at
    near-machine precision (the misspecification is identical on both sides).
    """
    spdcm = SpectralDCM(n_rois=2, TR=1.0)
    theta_true = np.array([0.4, 0.6, np.log(0.05)])

    y_clean = spdcm.predict_csd(theta_true)
    theta_init = np.array([0.0, 0.0, np.log(0.1)])

    res = _fit_spectral_lsq(spdcm, y_clean, theta_init)

    assert res.success
    assert np.isclose(res.x[0], theta_true[0], atol=2e-2)
    assert np.isclose(res.x[1], theta_true[1], atol=2e-2)
    assert np.isclose(res.x[2], theta_true[2], atol=0.1)


def test_3roi_spectral_recovers_theta_from_clean_csd():
    """3-ROI LS-spDCM self-consistency smoke for the clean CSD path."""
    spdcm = SpectralDCM(n_rois=3, TR=1.0, n_freqs=12)
    theta_true = np.array(
        [
            0.35,  # a01
            0.0,   # a02
            0.0,   # a10
            0.25,  # a12
            -0.15, # a20
            0.0,   # a21
            np.log(0.08),
        ]
    )

    y_clean = spdcm.predict_csd(theta_true)
    theta_init = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, np.log(0.1)])

    res = _fit_spectral_lsq(spdcm, y_clean, theta_init)

    assert res.success
    np.testing.assert_allclose(res.x[:6], theta_true[:6], atol=5e-2)
    assert np.isclose(res.x[6], theta_true[6], atol=0.15)


def test_spectral_recovers_theta_from_noisy_csd():
    """With structured Hermitian noise (snr=20), connectivity recovery within
    ~0.1, log_sigma_e within ~0.4."""
    spdcm = SpectralDCM(n_rois=2, TR=1.0)
    theta_true = np.array([0.4, 0.6, np.log(0.05)])

    rng = np.random.default_rng(0)
    y_noisy = spdcm.generate_noisy_csd(theta_true, snr=20.0, rng=rng)
    theta_init = np.array([0.0, 0.0, np.log(0.1)])

    res = _fit_spectral_lsq(spdcm, y_noisy, theta_init)

    assert res.success
    assert np.isclose(res.x[0], theta_true[0], atol=0.15)
    assert np.isclose(res.x[1], theta_true[1], atol=0.15)
    assert np.isclose(res.x[2], theta_true[2], atol=0.5)


def test_spectral_simulate_bold_fit_bias_within_documented_bounds():
    """Bias-bounding test (not a recovery test).

    ``simulate_bold`` integrates the FULL nonlinear Balloon ODE driven by an
    Itô SDE on the neural state. ``predict_csd`` is the *linearised* spDCM
    forward model. By design these are not bit-equivalent — fitting one with
    the other has an inherent bias from the linearisation around the
    haemodynamic operating point (q = v = f = 1, s = 0).

    This test pins the *magnitude* of that bias so a regression that makes
    things meaningfully worse — a sign error in the simulator, a regression
    in the H1 HRF fix, a change in the Balloon nonlinearity — would fail the
    test. Tolerances are wide on purpose; they characterise the linearisation
    gap, not the optimiser quality.
    """
    spdcm = SpectralDCM(n_rois=2, TR=1.0)
    theta_true = np.array([0.3, 0.5, np.log(0.1)])

    rng = np.random.default_rng(42)
    bold, _ = spdcm.simulate_bold(theta_true, T=2000, rng=rng)
    y_obs = spdcm.observed_csd(bold, nperseg=400, noverlap=200)

    theta_init = np.array([0.0, 0.0, np.log(0.2)])
    res = _fit_spectral_lsq(spdcm, y_obs, theta_init)

    assert res.success
    # Empirically observed bias magnitudes for this seed/settings:
    #   |a01_hat - 0.3| ≈ 0.54, |a10_hat - 0.5| ≈ 0.50,
    #   |log_sigma_e_hat - log(0.1)| ≈ 1.0
    # Loose bounds keep this test informative without being flaky.
    assert abs(res.x[0] - theta_true[0]) < 0.7
    assert abs(res.x[1] - theta_true[1]) < 0.7
    assert abs(res.x[2] - theta_true[2]) < 1.5


def test_hrf_spectrum_tr_scaling_is_consistent():
    """HRF spectrum at TR=2 should be approximately equal to TR=1 (same physics).

    Guards ``self.TR * np.fft.rfft(h)`` in ``_compute_hrf_spectrum``.  If the
    TR factor is removed, SpectralDCM(TR=2).hrf_spectrum drops by ½ relative to
    SpectralDCM(TR=1).hrf_spectrum because the Riemann sum has half as many terms.
    The CSD (proportional to |hrf_spectrum|²) would then be 4× too low for TR=2,
    creating a TR-dependent units mismatch vs observed_csd (Welch density in
    [BOLD]²/Hz).

    Expected ratio with correct scaling:  ~0.83  (same integral, ~20% from
    coarser 2-s sampling of the HRF).
    Expected ratio without TR scaling:    ~0.42  (misses the factor-of-2 from TR).
    Threshold of 0.6 cleanly separates the two cases.
    """
    s1 = SpectralDCM(n_rois=2, TR=1.0)
    s2 = SpectralDCM(n_rois=2, TR=2.0)

    ratio = np.mean(np.abs(s2.hrf_spectrum)) / np.mean(np.abs(s1.hrf_spectrum))
    assert ratio > 0.6, (
        f"hrf_spectrum TR=2/TR=1 ratio {ratio:.3f} < 0.6; "
        "possible missing TR factor in _compute_hrf_spectrum"
    )
