"""Verify H1: does SpectralDCM.predict_csd carry an extra |jw - lambda|^-2 factor?

H1 hypothesis:
    The HRF in spectral.py is built by driving a 1-ROI DCM with a 1-second boxcar
    INPUT through C=1, so the resulting kernel includes the 1-ROI neural filter
    (jw - self_connection)^-1 in addition to the haemodynamic kernel. predict_csd
    then re-multiplies by the multi-ROI H_neural = (jwI - A)^-1, double-counting
    the diagonal dynamics.

Test: build an "expected" 2-ROI CSD using the package's own hrf_spectrum (so we
share whatever Balloon scaling is in there) but with the neural transfer
function applied EXACTLY ONCE, then compare to predict_csd. If H1 is real, the
ratio predict_csd / expected should equal diag(|jw - lambda|^-2) on the
diagonals (and the off-diagonals should differ by a related factor).

We also build a "corrected" CSD that explicitly divides out (jw + 1)^-1 from
H_hrf and check whether predict_csd matches the model that does NOT
double-count. The two checks together pin down the bug magnitude.
"""

from __future__ import annotations

import numpy as np

from dcsem.spectral import SpectralDCM, _build_A_matrix


def expected_csd_single_neural_transfer(
    spdcm: SpectralDCM, theta: np.ndarray
) -> np.ndarray:
    """Build the CSD that the standard spDCM formulation would predict, using
    the package's hrf_spectrum AS-IS (so any Balloon scaling cancels in the
    comparison)."""
    R = spdcm.n_rois
    n_A = R * (R - 1)
    sigma_e = np.exp(theta[n_A])
    A = _build_A_matrix(theta[:n_A], R, spdcm.self_connection)

    S_stack = np.zeros((len(spdcm.freqs), R, R), dtype=complex)
    for k, f in enumerate(spdcm.freqs):
        omega = 2 * np.pi * f
        H_neural = np.linalg.solve(1j * omega * np.eye(R) - A, np.eye(R))
        H_hrf = np.diag([spdcm.hrf_spectrum[k]] * R)
        H_tot = H_hrf @ H_neural
        S = sigma_e**2 * (H_tot @ H_tot.conj().T)
        S_stack[k] = 0.5 * (S + S.conj().T)
    return S_stack


def expected_csd_corrected(spdcm: SpectralDCM, theta: np.ndarray) -> np.ndarray:
    """Build the CSD using a CORRECTED HRF: divide out the 1-ROI neural transfer
    function (jw - self_connection)^-1 that is implicitly baked into the package
    hrf_spectrum (because it was generated by driving a 1-ROI DCM through C=1).
    """
    R = spdcm.n_rois
    n_A = R * (R - 1)
    sigma_e = np.exp(theta[n_A])
    A = _build_A_matrix(theta[:n_A], R, spdcm.self_connection)
    lam = spdcm.self_connection

    S_stack = np.zeros((len(spdcm.freqs), R, R), dtype=complex)
    for k, f in enumerate(spdcm.freqs):
        omega = 2 * np.pi * f
        # Strip the 1-ROI neural filter from hrf_spectrum
        h_corrected = spdcm.hrf_spectrum[k] * (1j * omega - lam)
        H_neural = np.linalg.solve(1j * omega * np.eye(R) - A, np.eye(R))
        H_hrf = np.diag([h_corrected] * R)
        H_tot = H_hrf @ H_neural
        S = sigma_e**2 * (H_tot @ H_tot.conj().T)
        S_stack[k] = 0.5 * (S + S.conj().T)
    return S_stack


def main():
    spdcm = SpectralDCM(n_rois=2, TR=1.0, self_connection=-1.0)
    theta = np.array([0.4, 0.6, np.log(0.05)])

    # 1. predict_csd output (what the package actually computes)
    actual_vec = spdcm.predict_csd(theta)
    actual = spdcm._unvectorize_csd(actual_vec)

    # 2. CSD assuming the standard spDCM formula and the package's hrf_spectrum
    #    -- this is what predict_csd looks LIKE it is computing.
    expected = expected_csd_single_neural_transfer(spdcm, theta)

    # 3. CSD if we strip the implicit 1-ROI filter from hrf_spectrum first
    corrected = expected_csd_corrected(spdcm, theta)

    print("=" * 72)
    print("H1 verification: SpectralDCM HRF double-count")
    print("=" * 72)
    print(f"theta = {theta}")
    print(f"self_connection (lambda) = {spdcm.self_connection}")
    print(
        f"freqs = [{spdcm.freqs[0]:.4f}, ..., {spdcm.freqs[-1]:.4f}] Hz "
        f"(n={len(spdcm.freqs)})"
    )
    print()

    # Sanity: predict_csd should equal expected -- they use the SAME pipeline
    # except for the floating-point ordering. If this differs, our reference
    # build is wrong.
    sanity = np.max(np.abs(actual - expected))
    print("Sanity (predict_csd vs hand-built same-formula reference):")
    print(f"  max|predict - expected| = {sanity:.2e}  (should be ~0)")
    print()

    # The real test: ratio predict/corrected should equal |jw - lambda|^-2 on
    # the diagonal IF the HRF double-counts (because predict_csd = corrected *
    # |jw - lambda|^-2). Equivalently, predict_csd / corrected should be a
    # diagonal scalar = |hrf_spectrum / corrected_hrf|^2 = 1/|jw - lambda|^2.
    print("Diagonal ratio predict_csd / corrected at each frequency:")
    print("  (if H1 holds, this should equal |jw - lambda|^-2 = 1/(w^2 + 1))")
    print()
    print(
        f"  {'f (Hz)':>8} {'pred[0,0]':>14} {'corr[0,0]':>14} "
        f"{'ratio':>10} {'1/(w^2+1)':>10}"
    )
    for k in [0, 5, 10, 15, 20, 25, 31]:
        f = spdcm.freqs[k]
        omega = 2 * np.pi * f
        ratio = actual[k, 0, 0].real / corrected[k, 0, 0].real
        theory = 1.0 / (omega**2 + spdcm.self_connection**2)
        print(
            f"  {f:8.4f} {actual[k, 0, 0].real:14.4e} "
            f"{corrected[k, 0, 0].real:14.4e} {ratio:10.4f} {theory:10.4f}"
        )
    print()

    # Aggregate fit: diagonal ratio across all frequencies vs theory
    diag_ratio = np.array(
        [
            actual[k, 0, 0].real / corrected[k, 0, 0].real
            for k in range(len(spdcm.freqs))
        ]
    )
    theory = np.array(
        [1.0 / ((2 * np.pi * f) ** 2 + spdcm.self_connection**2) for f in spdcm.freqs]
    )
    rel_err = np.max(np.abs(diag_ratio - theory) / np.abs(theory))
    print(f"max|diag_ratio - 1/(w^2+1)| / |1/(w^2+1)| = {rel_err:.4e}")
    print()

    # Final verdict
    print("VERDICT")
    print("-" * 72)
    if rel_err < 1e-3:
        print("  CONFIRMED: predict_csd carries the extra |jw - lambda|^-2 factor")
        print("  on the diagonal. H1 is real.")
    elif rel_err < 0.1:
        print(f"  LIKELY: ratio matches theory to within {rel_err:.1%} relative")
        print("  error. The discrepancy may be from the 1-second boxcar (not a")
        print("  true Dirac) or zero-padded FFT interpolation.")
    else:
        print("  REJECTED: ratio does not match the |jw - lambda|^-2 prediction")
        print(f"  (rel error {rel_err:.2%}). H1 needs reformulation.")
    print()

    # Magnitude of bias: how much does the extra factor distort the spectrum
    # over the audit-relevant 0.01-0.1 Hz band?
    band_distortion_pct = (theory.max() - theory.min()) / theory.max() * 100
    print("Magnitude of distortion across 0.01-0.1 Hz:")
    print(f"  diagonal magnitude varies by {band_distortion_pct:.1f}% across band")
    print(
        f"  ({100 * (1 - theory.max()):.2f}% at f_lo, "
        f"{100 * (1 - theory.min()):.2f}% at f_hi)"
    )


if __name__ == "__main__":
    main()
